// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RestaurantSystem.Data.Data;

#nullable disable

namespace RestaurantSystem.Data.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PartialId")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartialId");

                    b.ToTable("PartialEntityBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PartialEntityBase");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContactPartialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentEventPartialId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentEventsPartialId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentMenuPartialId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterCenterInfoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftBoxDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftBoxPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftBoxTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoFacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoLinkedinLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterLeftInfoTwitterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterRightInfoButtonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterRightInfoButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterRightInfoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterRightInfoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TopBarCenterPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopBarLeftInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopBarLeftPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopBarRightInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopBarRightPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopbarCenterTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopbarLeftTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopbarRightTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteTitlePart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactPartialId");

                    b.HasIndex("CurrentEventPartialId");

                    b.HasIndex("CurrentMenuPartialId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContactPage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndexPage")
                        .HasColumnType("bit");

                    b.Property<string>("LinkTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Partial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsForMainPage")
                        .HasColumnType("bit");

                    b.Property<int?>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("PartialButtonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartialButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartialType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Partial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitPriceGross")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<decimal?>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.AboutPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<string>("LeftContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightPhotoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AboutPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.ContactPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<string>("CompanyDataContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDataTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDataContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactDataTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormButtonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneDataContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneDataTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ContactPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.CurrentEventPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CurrentEventPartial_PhotoName");

                    b.HasDiscriminator().HasValue("CurrentEventPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.CurrentMenuPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CurrentMenuPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.FactPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<long?>("Count")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("FactPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.HeroPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<string>("HeroButtonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HeroPartial_PhotoName");

                    b.Property<string>("VideoModalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("HeroPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.OpinionPartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("OpinionPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.ServicePartial", b =>
                {
                    b.HasBaseType("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ServicePartial_EventDate");

                    b.Property<string>("EventInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServicePartial_EventInfo");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServicePartial_FacebookLink");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServicePartial_LinkedinLink");

                    b.Property<string>("PhotoName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServicePartial_PhotoName");

                    b.HasDiscriminator().HasValue("ServicePartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Abstract.PartialEntityBase", b =>
                {
                    b.HasOne("RestaurantSystem.Data.Data.CMS.Partial", "Partial")
                        .WithMany("PartialEntityBases")
                        .HasForeignKey("PartialId");

                    b.Navigation("Partial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Company", b =>
                {
                    b.HasOne("RestaurantSystem.Data.Data.CMS.ContactPartial", "ContactPartial")
                        .WithMany()
                        .HasForeignKey("ContactPartialId");

                    b.HasOne("RestaurantSystem.Data.Data.CMS.CurrentEventPartial", "CurrentEventPartial")
                        .WithMany("Companies")
                        .HasForeignKey("CurrentEventPartialId");

                    b.HasOne("RestaurantSystem.Data.Data.CMS.CurrentMenuPartial", null)
                        .WithMany("Companies")
                        .HasForeignKey("CurrentMenuPartialId");

                    b.Navigation("ContactPartial");

                    b.Navigation("CurrentEventPartial");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Partial", b =>
                {
                    b.HasOne("RestaurantSystem.Data.Data.CMS.Page", "Page")
                        .WithMany("Partials")
                        .HasForeignKey("PageId");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Product", b =>
                {
                    b.HasOne("RestaurantSystem.Data.Data.CMS.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Page", b =>
                {
                    b.Navigation("Partials");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.Partial", b =>
                {
                    b.Navigation("PartialEntityBases");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.CurrentEventPartial", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("RestaurantSystem.Data.Data.CMS.CurrentMenuPartial", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
